- hosts: localhost
  roles:
  - role: inventory_hosts
- hosts: "{{ playbook_hosts | default('ydb') }}"
  tasks:
    - name: setup ydb static nodes
      ansible.builtin.import_role:
        name: ydb_platform.ydb.ydbd_static
